// Auto-generated by `supabase gen types` — DO NOT EDIT MANUALLY
// Placeholder until Supabase project is connected

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      categories: {
        Row: {
          id: string;
          slug: string;
          name: Json;
          display_order: number;
        };
        Insert: {
          id?: string;
          slug: string;
          name: Json;
          display_order?: number;
        };
        Update: {
          id?: string;
          slug?: string;
          name?: Json;
          display_order?: number;
        };
      };
      products: {
        Row: {
          id: string;
          slug: string;
          category_id: string | null;
          name: Json;
          description: Json | null;
          price_xof: number;
          images: string[];
          is_available: boolean;
          is_featured: boolean;
          stock_note: string | null;
          meta_title: Json | null;
          meta_description: Json | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          slug: string;
          category_id?: string | null;
          name: Json;
          description?: Json | null;
          price_xof: number;
          images?: string[];
          is_available?: boolean;
          is_featured?: boolean;
          stock_note?: string | null;
          meta_title?: Json | null;
          meta_description?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          slug?: string;
          category_id?: string | null;
          name?: Json;
          description?: Json | null;
          price_xof?: number;
          images?: string[];
          is_available?: boolean;
          is_featured?: boolean;
          stock_note?: string | null;
          meta_title?: Json | null;
          meta_description?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      orders: {
        Row: {
          id: string;
          product_id: string | null;
          product_snapshot: Json;
          customer_name: string | null;
          customer_phone: string | null;
          note: string | null;
          status: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          product_id?: string | null;
          product_snapshot: Json;
          customer_name?: string | null;
          customer_phone?: string | null;
          note?: string | null;
          status?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          product_id?: string | null;
          product_snapshot?: Json;
          customer_name?: string | null;
          customer_phone?: string | null;
          note?: string | null;
          status?: string;
          created_at?: string;
        };
      };
      shop_config: {
        Row: {
          key: string;
          value: string;
          updated_at: string;
        };
        Insert: {
          key: string;
          value: string;
          updated_at?: string;
        };
        Update: {
          key?: string;
          value?: string;
          updated_at?: string;
        };
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
}
